### PR TITLE
Dr D Fun Test Branch

### PR DESCRIPTION
**Pull request by mdaugherity**
This is a test

### CODE REVIEW

**Review by mskrta — APPROVED** [review]
Ok

**Comment by cjc19e** [comment]
looks good!

**Review by Phoebe040 — APPROVED** [review]
fun test branch should be capitalized but ok

**Comment by mdaugherity** [comment]
Hey this code stinks!

**Comment by Erik-424** [comment]
No it doesn't!

**Comment by mskrta** [comment]
Not biblically accurate

**Review by MrJHembree — APPROVED** [review]
Nice!

**Review by Erik-424 — APPROVED** [review]

**Review by cjc19e — APPROVED** [review]

**Review by mdaugherity — COMMENTED** [review]
This code rocks!

**Comment by Erik-424** [comment]
The best code I've ever seen.

**Pull request merged**
